baseURL = 'https://nullnyat.nca10.net/'
title = 'nullnyat.nca10.net'
author = 'nullnyat'
HasCJKLanguage = true
DefaultContentLanguage = 'ja'
languageCode = 'ja-jp'
enableRobotsTXT = true
pluralizeListTitles = false
markup.highlight.noClasses = false

[Params]
dateformat = '2006/01/02'
description = 'ぬるにゃウェブページ'

[taxonomies]
tag = 'tags'
category = 'categories'
archive = 'archives'

[markup.goldmark.renderer]
unsafe = true

[outputs]
 home = ['html', 'rss']
 section = ['html', 'rss']
 taxonomy = ['html']
 term = ['html']

disableKinds = ['rss']

[services]
 [services.rss]
 limit = 42
 copyright = '© 2024 nullnyat'

[params]
 [params.author]
  email = 'nullnyat@nca10.moe'
  name = 'nullnyat'